### ISSUE TITLE
갑작스럽게 torchvision 에러가 발생합니다.

### ISSUE THREAD

**Issue by jjxxmiin** [AI-RUSH-Operation/NAVER-AI-RUSH#101]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your login ID?**

jjeamin

**Question**
```
Traceback (most recent call last):
  File "main_cv.py", line 6, in <module>
    import torchvision
  File "/usr/local/lib/python3.6/dist-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py", line 43, in <module>
    @torch.jit._script_if_tracing
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
```

원래 오류가 없다가 torchvision을 import할 때 갑자기 오류가 계속 발생합니다.

**Comment by nsml-admin** [comment]
안녕하세요..
확인해보니 torchvision이 최근에 업데이트 되었네요 https://pypi.org/project/torchvision/#history 
setup.py에 예전버전을 fix하고 해보실래요?

**Comment by jjxxmiin** [comment]
version 문제가 맞네요 감사합니다 ㅎㅎ
